services:
  bot:
    build: .
    restart: always
    env_file:
      - .env
    volumes:
      - bot_data:/data

  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./dozzle-data:/data
    ports:
      - "8080:8080"
    environment:
      DOZZLE_AUTH_PROVIDER: simple

volumes:
  bot_data:
